//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteDetail
    {
        public decimal ID { get; set; }
        public decimal RouteID { get; set; }
        public int StopNo { get; set; }
        public decimal StopID { get; set; }
        public double DistanceFromPrevStop { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual Stop Stop { get; set; }
    }
}
